//
//  DeviceModelName.swift
//  DeviceSpec
//
//  Created by Дмитрий Кулешов on 27.11.2020.
//

import Foundation

public enum DeviceModelName: String {
    case undefined
    case iPodTouch1 = "iPod Touch 1st"
    case iPodTouch2 = "iPod Touch 2st"
    case iPodTouch3 = "iPod Touch 3st"
    case iPodTouch4 = "iPod Touch 4st"
    case iPodTouch5 = "iPod Touch 5st"
    case iPodTouch6 = "iPod Touch 6st"
    case iPodTouch7 = "iPod Touch 7st"
    case iPhone = "iPhone 1stn"
    case iPhone3G = "iPhone 3G"
    case iPhone3GS = "iPhone 3GS"
    case iPhone4 = "iPhone 4"
    case iPhone4s = "iPhone 4s"
    case iPhone5 = "iPhone 5"
    case iPhone5c = "iPhone 5C"
    case iPhone5s = "iPhone 5S"
    case iPhone6 = "iPhone 6"
    case iPhone6Plus = "iPhone 6 Plus"
    case iPhone6s = "iPhone 6S"
    case iPhone6sPlus = "iPhone 6S Plus"
    case iPhone7 = "iPhone 7"
    case iPhone7Plus = "iPhone 7 Plus"
    case iPhoneSE = "iPhone SE"
    case iPhone8 = "iPhone 8"
    case iPhone8Plus = "iPhone 8 Plus"
    case iPhoneX = "iPhone X"
    case iPhoneXS = "iPhone XS"
    case iPhoneXSMax = "iPhone XS Max"
    case iPhoneXR = "iPhone XR"
    case iPhone11 = "iPhone 11"
    case iPhone11Pro = "iPhone 11 Pro"
    case iPhone11ProMax = "iPhone 11 Pro Max"
    case iPhoneSE2 = "iPhone SE 2nd"
    case iPhone12Mini = "iPhone 12 mini"
    case iPhone12 = "iPhone 12"
    case iPhone12Pro = "iPhone 12 Pro"
    case iPhone12ProMax = "iPhone 12 Pro Max"
    case iPad1 = "iPad 1"
    case iPad2 = "iPad 2"
    case iPad3 = "iPad 3"
    case iPad4 = "iPad 4"
    case iPadAir = "iPad Air"
    case iPadAir2 = "iPad Air 2nd"
    case iPad5 = "iPad 5"
    case iPad6 = "iPad 6"
    case iPadMini = "iPad Mini"
    case iPadMini2 = "iPad Mini 2"
    case iPadMini3 = "iPad Mini 3"
    case iPadMini4 = "iPad Mini 4"
    case iPadPro97Inch = "iPad Pro 9.7\""
    case iPadPro129Inch = "iPad Pro 12.9\""
    case iPadPro129Inch2ndGen = "iPad Pro 12.9\" 2nd"
    case iPadPro105Inch = "iPad Pro 10.5\""
    case iPadPro11Inch = "iPad Pro 11\""
    case iPadPro129Inch3rdGen = "iPad Pro 12.9\" 3rd"
    case iPadPro4th11inch = "iPad Pro 11\" 4th"
    case iPadPro4th12inch = "iPad Pro 12\" 4th"
    case iPadMini5 = "iPad Mini 5"
    case iPadAir3rd = "iPad Air 3rd"
    case iPad8th = "iPad 8"
    case iPadAir4th  = "iPad Air 4th"
    case watch = "Watch"
    case watch1 = "Watch 1"
    case watch2 = "Watch 2"
    case watch3 = "Watch 3"
    case watch4 = "Watch 4"
    case watch5 = "Watch 5"
    
    case appleTV = "Apple TV"
    case appleTV4K = "Apple TV 4K"
    case homePod  = "Home Pod"
    case simulator
}
